### ISSUE TITLE
Adding class names or hooks into react code

### ISSUE THREAD

**Issue by jg314** [johngodley/redirection#2040]
The is much more of a feature request than a bug. The plugin itself is great. 

### Summary

We're hoping to use it on a multisite installation for a number of clients and would love to simplify the user experience for them. There is a ton of neat functionality in the plugin, but we'd love to avoid confusing our clients with the extra features. Here is how the interface looks normally:

![redirection-full-functionality](https://user-images.githubusercontent.com/1054379/67426973-c6c6ca80-f5a0-11e9-9b5e-a20630f38bbb.jpg)

And here is what we're trying to accomplish:

![redirection-simplified-functionality](https://user-images.githubusercontent.com/1054379/67426983-cdedd880-f5a0-11e9-8a4b-8d8e821b7dcf.jpg)

We've been able to accomplish this using the following CSS:

```css
.redirection .subsubsub-container,
.redirection .redirect-table-display__filter,
.redirection select[name="group"],
.redirection .redirect-multioption,
.redirection .redirection-edit_advanced,
.redirection table.edit-redirection tr:nth-child(2),
.redirection table.edit-redirection tr:nth-child(4),
.redirection .redirect-searchbox .redirect-dropdownbutton li:nth-child(3),
.redirection-poweredby {
	display: none;
}
```

We obviously don't love this approach since the selectors are so vague and can easily cause problems when the plugin is updated. Specifically, we're worried about the `nth-child()` selectors.

Is there any chance you'd be open to adding class names in your react code to many of these elements so they're easier to target? If that's not possible, could you provide hooks through JavaScript or PHP to allow us to remove the elements there?

Thanks a ton.
